### ISSUE TITLE
arduino ve display bağlantısı

### ISSUE THREAD

**Issue by xcawhy** [firatsoygul/LC75823#1]
Merhaba, Çalışmanız için tebrik ederim. Bende de aynı lcd display mevcut ve değerlendirmek istedim. Ama arduino ve display bağlantılarını belirtmemişsiniz. [PT6523](https://github.com/firatsoygul/PT6523) çalışmanızdaki gibi bağlantıları belirten bir şema yada foto koyarsanız sevinirim. İyi çalışmalar.

**Comment by firatsoygul** [comment]
Kusura bakmayın geri dönüşüm uzun sürdü. Karta ait bir [baglantı şeması](https://raw.githubusercontent.com/firatsyg/LC75823/master/img/baglanti.jpg) ekledim.  

Betik standart Arduino SPI kütüphanesini kullanıyor. Bu nedenle; 

- Data hattını Arduino 11 nolu pine (veya ICSP soketi üzerindeki 4 nolu MOSI pinine), 
- CLK'yı ise Arduino 13 nolu pine (veya ICSP soketi üzerindeki 3 nolu SCK pinine), 
- FCE girişini Arduino 10 nolu pine bağlamak gerekiyor.
 
Bu pinler Arduino Uno modeli için geçerli. Diğer Arduino modelleri için bu sayfadaki [tabloya bakabilirsiniz](https://www.arduino.cc/en/Reference/SPI). FCE girişini ise bütün modellerde Arduino 10 nolu pine bağlıyoruz. Veya "slaveSelectPin" değişkenini başka bir pine ayarlayabilirsiniz. 

~~Henüz ayrı bir kütüphane haline getirmedim, fakat betiği bu haliyle uygulamanız içerisine gömerek, kayar şekilde yazı yazdırabilirsiniz.~~ 

İyi çalışmalar.

**Comment by firatsoygul** [comment]
Betiği kütüphane haline getirdim. [Readme](https://github.com/firatsoygul/LC75823/blob/master/README.md) dosyasından ayrıntılara bakabilirsiniz.
